CREATE TABLE general_information (
     id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
     postcode varchar(6),
     huisnummer smallint(6),
     premium_avp tinyint(1),
     premium_buiten tinyint(1),
     premium_inboedel tinyint(1),
     premium_ongevallen tinyint(1),
     premium_rechtsbijstand tinyint(1),
     premium_reis tinyint(1),
     premium_woonhuis tinyint(1),
     soort_verzekering varchar(255),
     maatschappij_een varchar(255),
     polisnummer varchar(255),
     soort_dekking varchar(255),
     verzekerd_bedrag int(11),
     datum DATE,
     eventueleOpzegging varchar(255),
     uzelf tinyint(1),
     intermediair tinyint(1),
     aantal_schades int,
     laatste_schadeclaim DATE,
     totaal_bedrag int,
     beschrijving varchar(255),
     maatschappij_vier varchar(255),
     polisnummer_vier varchar(255),
     toelichting varchar(255)
);